-- OptiFi - PostgreSQL schema v1 (fresh database)

drop table if exists public.budget_categories cascade;
drop table if exists public.budget_accounts cascade;
drop table if exists public.budgets cascade;

drop table if exists public.transactions cascade;
drop table if exists public.accounts cascade;
drop table if exists public.categories cascade;
drop table if exists public.users cascade;

create table public.users
(
    id               bigint generated by default as identity primary key,
    username         varchar(32)                 not null,
    email            varchar(100)                not null,
    auth_provider    varchar(255)                not null,
    provider_subject varchar(255),
    password_hash    varchar(255),
    role             varchar(255)                not null default 'USER'
        constraint users_role_check
            check (role in ('ADMIN', 'MODERATOR', 'USER', 'WAITING_APPROVAL', 'BLOCKED')),
    locale           varchar(16)                 not null
        constraint users_locale_check
            check (locale in ('BG_BG', 'EN_US')),
    time_zone_id     varchar(64),
    base_currency    varchar(255)                not null
        constraint users_base_currency_check
            check (base_currency in ('USD', 'EUR')),
    created_at       timestamp(6) with time zone not null,
    updated_at       timestamp(6) with time zone,

    constraint uk_users_username unique (username),
    constraint uk_users_email unique (email),
    constraint uk_users_provider_subject unique (auth_provider, provider_subject)
);

create index idx_users_email on public.users (email);
create index idx_users_username on public.users (username);


create table public.accounts
(
    id          bigint generated by default as identity primary key,
    user_id     bigint                      not null
        constraint fk_accounts_user
            references public.users (id),
    name        varchar(32)                 not null,
    institution varchar(100),
    currency    varchar(255)                not null
        constraint accounts_currency_check
            check (currency in ('USD', 'EUR')),
    type        varchar(255)                not null
        constraint accounts_type_check
            check (type in ('CASH', 'BANK')),
    archived    boolean                     not null default false,
    created_at  timestamp(6) with time zone not null,
    updated_at  timestamp(6) with time zone,

    constraint uk_user_account_name unique (user_id, name)
);

create index idx_accounts_user_id on public.accounts (user_id);
create index idx_accounts_active_by_user on public.accounts (user_id) where archived = false;


create table public.categories
(
    id          bigint generated by default as identity primary key,
    name        varchar(100)                not null,
    user_id     bigint
        constraint fk_categories_user
            references public.users (id),
    description varchar(255)                not null,
    icon        varchar(255)                not null,
    created_at  timestamp(6) with time zone not null,
    updated_at  timestamp(6) with time zone
);

create index idx_categories_user_id on public.categories (user_id);

create unique index uk_categories_default_name
    on public.categories (name)
    where user_id is null;

create unique index uk_categories_user_name
    on public.categories (user_id, name)
    where user_id is not null;


create table public.transactions
(
    id          bigint generated by default as identity primary key,
    account_id  bigint                      not null
        constraint fk_transactions_account
            references public.accounts (id),
    category_id bigint                      not null
        constraint fk_transactions_category
            references public.categories (id),
    amount      numeric(19, 4)              not null,
    description varchar(255),
    occurred_at timestamp(6) with time zone not null,
    created_at  timestamp(6) with time zone not null,
    updated_at  timestamp(6) with time zone
);

create index idx_transactions_account_occurred
    on public.transactions (account_id, occurred_at);

create index idx_transactions_category_occurred
    on public.transactions (category_id, occurred_at);


create table public.budgets
(
    id         bigint generated by default as identity primary key,
    user_id    bigint                      not null
        constraint fk_budgets_user
            references public.users (id),
    name       varchar(100)                not null,
    period     varchar(255)                not null
        constraint budgets_period_check
            check (period in ('WEEK', 'MONTH', 'YEAR')),
    amount     numeric(19, 4)              not null
        constraint budgets_amount_check
            check (amount >= 0),
    currency   varchar(255)                not null
        constraint budgets_currency_check
            check (currency in ('USD', 'EUR')),
    start_date date                        not null,
    end_date   date                        not null,
    archived   boolean                     not null default false,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone,

    constraint budgets_end_date_check
        check (end_date >= start_date),
    constraint uk_budgets_user_name unique (user_id, name)
);

create index idx_budgets_user_id on public.budgets (user_id);
create index idx_budgets_user_active_range on public.budgets (user_id, start_date, end_date) where archived = false;


create table public.budget_accounts
(
    budget_id  bigint not null
        constraint fk_budget_accounts_budget
            references public.budgets (id)
            on delete cascade,

    account_id bigint not null
        constraint fk_budget_accounts_account
            references public.accounts (id)
            on delete cascade,

    primary key (budget_id, account_id)
);

create index idx_budget_accounts_account_id on public.budget_accounts (account_id);


create table public.budget_categories
(
    budget_id   bigint not null
        constraint fk_budget_categories_budget
            references public.budgets (id)
            on delete cascade,

    category_id bigint not null
        constraint fk_budget_categories_category
            references public.categories (id)
            on delete cascade,

    primary key (budget_id, category_id)
);

create index idx_budget_categories_category_id on public.budget_categories (category_id);
